// <auto-generated />
using System;
using ECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Migrations
{
[DbContext(typeof(ApiDbContext))]
[Migration("20220923035854_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
        .HasAnnotation("ProductVersion", "6.0.9")
        .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("ECommerce.Domain.Models.Address", b =>
        {
            b.Property<Guid>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("uniqueidentifier");

            b.Property<string>("City")
            .IsRequired()
            .HasColumnType("varchar(30)");

            b.Property<string>("Complement")
            .HasColumnType("varchar(120)");

            b.Property<Guid>("CustomerId")
            .HasColumnType("uniqueidentifier");

            b.Property<string>("District")
            .IsRequired()
            .HasColumnType("varchar(50)");

            b.Property<string>("HouseNumber")
            .IsRequired()
            .HasColumnType("varchar(10)");

            b.Property<string>("PhoneNumber")
            .IsRequired()
            .HasColumnType("varchar(20)");

            b.Property<string>("State")
            .IsRequired()
            .HasColumnType("varchar(30)");

            b.Property<string>("Street")
            .IsRequired()
            .HasColumnType("varchar(50)");

            b.Property<string>("ZipCode")
            .IsRequired()
            .HasColumnType("varchar(10)");

            b.HasKey("Id");

            b.HasIndex("CustomerId");

            b.ToTable("Addresses", (string)null);
        });

        modelBuilder.Entity("ECommerce.Domain.Models.Customer", b =>
        {
            b.Property<Guid>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("BirthDate")
            .HasColumnType("datetime2");

            b.Property<DateTime?>("DeletedAt")
            .HasColumnType("datetime2");

            b.Property<string>("Email")
            .IsRequired()
            .HasColumnType("varchar(100)");

            b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("varchar(100)");

            b.Property<string>("Password")
            .IsRequired()
            .HasColumnType("varchar(20)");

            b.HasKey("Id");

            b.HasIndex("Email")
            .IsUnique();

            b.HasIndex("Name");

            b.ToTable("Customers", (string)null);
        });

        modelBuilder.Entity("ECommerce.Domain.Models.Address", b =>
        {
            b.HasOne("ECommerce.Domain.Models.Customer", "Customer")
            .WithMany("Addresses")
            .HasForeignKey("CustomerId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

            b.Navigation("Customer");
        });

        modelBuilder.Entity("ECommerce.Domain.Models.Customer", b =>
        {
            b.Navigation("Addresses");
        });
#pragma warning restore 612, 618
    }
}
}
